#!/usr/bin/php
<?php

require_once __DIR__  . '/../vendor/autoload.php';

$app = new Skeleton\Application();
$app->router()->addRoutes([
    'hello <name>' => [
        'controller' => 'Skeleton\Controller\ConsoleController',
        'action'     => 'hello',
        'default'    => true
    ],
    'foo' => [
        'controller' => 'Skeleton\Controller\ConsoleController',
        'action'     => 'foo'
    ]
]);

$app->run();
