<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        Pop PHP Framework Skeleton Application
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0">

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link rel="stylesheet" type="text/css" href="css/styles.css" />

</head>

<body>
    <header>
        <h1><a href="http://www.popphp.org/" target="_blank">Pop PHP Framework Skeleton Application</a></h1>
    </header>
<!-- Content //-->
    <div id="content">
        <h1>Welcome to the Pop PHP Framework Skeleton Application</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin volutpat. Maecenas laoreet tempus quam. Maecenas faucibus semper leo. Nullam sit amet felis. Integer luctus interdum lacus. Vestibulum pulvinar, nunc a fermentum eleifend, dui ipsum condimentum urna, at hendrerit lacus mi elementum tortor. Maecenas lacus. Nunc varius. Duis malesuada. Vivamus facilisis quam et diam. Curabitur augue. Phasellus eros. Aliquam ultrices nisi lobortis pede. Curabitur ac augue id erat mollis commodo. Vestibulum nonummy iaculis risus. Quisque posuere. Curabitur cursus tellus sit amet purus.
        </p>
        <p>
            Aliquam velit massa, ultricies sit amet, facilisis vitae, placerat vitae, justo. Pellentesque tortor orci, ornare a, consequat ut, mollis et, nisl. Suspendisse sem metus, convallis nec, fermentum sed, varius at, metus. Pellentesque ullamcorper diam eget urna. Aliquam risus risus, imperdiet sit amet, elementum nec, pellentesque vel, justo. Quisque dictum sagittis dolor. Nam nulla. Duis id ipsum. Proin ultrices. Maecenas egestas malesuada erat. Nulla facilisi. In blandit auctor justo. Etiam sem nisi, mattis et, consequat non, suscipit quis, arcu. Quisque a diam. Etiam lorem arcu, gravida in, aliquet non, dapibus sed, sapien. Sed ut felis a justo condimentum tincidunt. Aliquam a magna. Mauris est.
        </p>
    </div>
<!-- Footer //-->
    <footer>
        Pop PHP Framework on <a href="https://github.com/popphp/" target="_blank">Github</a>.
    </footer>
</body>

</html>
